<?binding.jca CheckIfInspected_db.jca?>
<wsdl:definitions name="CheckIfInspected" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/GrnApprovalWorkflow/GrnApproval/CheckIfInspected" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/CheckIfInspected" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/GrnApprovalWorkflow/GrnApproval/CheckIfInspected" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="CheckIfInspected_plt">
        <plt:role name="CheckIfInspected_role">
            <plt:portType name="tns:CheckIfInspected_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CheckIfInspected" schemaLocation="xsd/CheckIfInspected.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="CheckIfInspectedInput_msg">
        <wsdl:part name="CheckIfInspectedInput_msg" element="db:CheckIfInspectedInput"/>
    </wsdl:message>
    <wsdl:message name="CheckIfInspectedOutputCollection_msg">
        <wsdl:part name="CheckIfInspectedOutputCollection" element="db:CheckIfInspectedOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="CheckIfInspected_ptt">
        <wsdl:operation name="CheckIfInspected">
            <wsdl:input message="tns:CheckIfInspectedInput_msg"/>
            <wsdl:output message="tns:CheckIfInspectedOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
