<?binding.jca PollRcvShipmentHeaders_db.jca?>
<wsdl:definitions name="PollRcvShipmentHeaders" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/GrnApprovalWorkflow/GrnApproval/PollRcvShipmentHeaders" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/GrnApprovalWorkflow/GrnApproval/PollRcvShipmentHeaders" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollRcvShipmentHeaders">
    <plt:partnerLinkType name="PollRcvShipmentHeaders_plt">
        <plt:role name="PollRcvShipmentHeaders_role">
            <plt:portType name="tns:PollRcvShipmentHeaders_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollRcvShipmentHeaders" schemaLocation="xsd/PollRcvShipmentHeaders_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="RcvShipmentHeadersCollection_msg">
        <wsdl:part name="RcvShipmentHeadersCollection" element="top:RcvShipmentHeadersCollection"/>
    </wsdl:message>
    <wsdl:portType name="PollRcvShipmentHeaders_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:RcvShipmentHeadersCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
