<?binding.jca UpdFlagCaseApproved_db.jca?>
<wsdl:definitions name="UpdFlagCaseApproved" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/GrnApprovalWorkflow/GrnApproval/UpdFlagCaseApproved" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/UpdFlagCaseApproved" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/GrnApprovalWorkflow/GrnApproval/UpdFlagCaseApproved" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="UpdFlagCaseApproved_plt">
        <plt:role name="UpdFlagCaseApproved_role">
            <plt:portType name="tns:UpdFlagCaseApproved_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/UpdFlagCaseApproved" schemaLocation="xsd/UpdFlagCaseApproved.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="UpdFlagCaseApprovedInput_msg">
        <wsdl:part name="UpdFlagCaseApprovedInput_msg" element="db:UpdFlagCaseApprovedInput"/>
    </wsdl:message>
    <wsdl:portType name="UpdFlagCaseApproved_ptt">
        <wsdl:operation name="UpdFlagCaseApproved">
            <wsdl:input message="tns:UpdFlagCaseApprovedInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
